name: paper_trails
description: "OCR scanning & record-keeping app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  google_ml_kit: ^0.16.3
  path_provider: ^2.1.2
  sqflite: ^2.3.2
  path: ^1.9.0
  intl: ^0.20.2
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  package_info_plus: ^4.0.0
  share_plus: ^8.0.0
  pdf: ^3.10.1
  printing: ^5.9.0
  cupertino_icons: ^1.0.8
  crop_your_image: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^14.0.0
  flutter_native_splash: ^2.2.10

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  



# Rename the app’s display name

flutter_launcher_name:
  name: "PaperTrails"

# Generate launcher icons from this source image

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  remove_alpha: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
